### ISSUE TITLE
Please do "npm run validate:html" and send screenshot to this thread

### ISSUE THREAD

**Issue by rudnitskih** [JukaChu/sports-app-landing#12]
I am not sure if you have completely valid HTML

**Comment by JukaChu** [comment]
![image](https://user-images.githubusercontent.com/48647343/56734404-65e24500-676b-11e9-8f07-11d321893831.png)

**Comment by rudnitskih** [comment]
Ага, првоерил: 
Я всегда думал что в `section` должен быть какойто заголовок - если его нет, то это не section а просто `div`. В том случае в каждой секции можно поставить h1.

Но это необязательно кака оказлось - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section
