### ISSUE TITLE
Недочёты 2

### ISSUE THREAD

**Issue by heywhahappnd** [JukaChu/sports-app-landing#2]
https://github.com/JukaChu/sports-app-landing/blob/bfbd77bfed67541fcb5b9059e561745fd1c4d4a9/src/index.html#L51-L78

1)Если ты всё оборачиваешь в section , этот кусок(ссылка сверху) тоже должен быть внутри секции
2)Со следующим section всё в порядке , только у тебя `<h2>What Our Users Say</h2>` вне секции.
3) У тебя там section с твиттер постами , оберни это в article , например article>(h2+section*4)
Всё остальное в принципе хорошо

**Comment by JukaChu** [comment]
Если привязать `<h2>What Our Users Say</h2>` к секции, тогда он будет связан с этим твитом `<section>
      <h3>Noah Jackson</h3>
      <a href="javascript:void(0)"><img src="img/twitter.png" alt="twitter"></a>
      <p>I use this app every day and it's a great way to keep up to date with what's going on in football. It's a shame
        it won't rotate into landscape mode like its main competitor</p>
    </section>` , привязывать?

**Comment by heywhahappnd** [comment]
ты всё правильно обернул уже
