### ISSUE TITLE
Check the positon of the background in the first section

### ISSUE THREAD

**Issue by heywhahappnd** [JukaChu/sports-app-landing#6]
Your h1 is almost on the top of the image. Check the example. You should have some margins

**Comment by JukaChu** [comment]
![image](https://user-images.githubusercontent.com/48647343/56098049-be604980-5f04-11e9-8b29-1172809d3cce.png) 
on the same height. can u send me pls more details?

**Comment by heywhahappnd** [comment]
http://joxi.ru/KAgNOzliEV7zQ2 - как у тебя
http://joxi.ru/J2bkKGpC0v5jXA - как на макете

**Comment by JukaChu** [comment]
все, понял. это из-за ширины дисплея, адаптивку я еще не начинал делать для этого задания. мне сделать что бы бэкграунд не уезжал?

![image](https://user-images.githubusercontent.com/48647343/56099049-d50c9d80-5f10-11e9-834e-b549990f2f0a.png)

**Comment by heywhahappnd** [comment]
Да
