### ISSUE TITLE
Поправь картинку на фоне

### ISSUE THREAD

**Issue by heywhahappnd** [JukaChu/sports-app-landing#7]
http://joxi.ru/KAgNOzliEjKJk2 - твоя страничка
http://joxi.ru/1A5MOnlhDvbWVA - макет

**Comment by rudnitskih** [comment]
@vladkaryakin Льоша сделал правильно на 1440px - оно выглядит как на макете. А на 1366 по другому я не вижу как правильней сделать. Я бы закрыл это issue
